language: php

php:
  - 5.5
  - 5.6
  - 7

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email:
    recipients:
      - portey@gmail.com
      - a@viniychuk.com
    on_success: change
    on_failure: always